import React from 'react'

const Career = () => {
    return (
        <div>
            <h1>Career</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum deserunt natus iure alias eveniet, soluta consequatur itaque, quasi, cupiditate minus quas dolores nihil atque repellendus rem reprehenderit? Optio fugiat aperiam necessitatibus, accusantium, harum repudiandae tempora iusto, officia sapiente consequatur aspernatur perferendis adipisci quod delectus sequi expedita voluptatum eum tempore! Commodi explicabo est dolor sint ducimus. Id, quam! Atque est nulla fuga, libero quas accusantium dignissimos doloremque veniam delectus eveniet maxime animi voluptatibus ad nesciunt possimus saepe ab laborum doloribus expedita rerum. Ad, aliquid. Recusandae alias repellendus, totam voluptatibus temporibus quisquam? Rerum, beatae, quasi itaque corporis doloremque illum, at totam libero laborum provident a. Quam sequi saepe rem doloribus quos, quis a vel aliquid eius vero repellendus quas illum molestias voluptatibus corporis laborum commodi, nisi recusandae nostrum reiciendis in modi sed id. Ab, ipsam accusantium. Consequuntur quisquam ex commodi, blanditiis esse qui distinctio enim quo debitis, eos, laborum eligendi totam dicta tempore pariatur. Dolore vitae sapiente modi delectus tempora eligendi, aperiam quidem architecto eius reiciendis rem aut praesentium provident non itaque deleniti. Facere, amet eaque quos nihil perspiciatis esse suscipit quis non, explicabo, voluptatum vel molestiae obcaecati quod! Perspiciatis voluptate qui consectetur officiis reiciendis eveniet quaerat, at dignissimos provident voluptates nobis a quas dolorum, labore natus est rerum fuga odio! Minus quam ut quidem provident magni quasi molestiae praesentium ipsa dolorem rerum? Animi voluptates vero enim, qui ullam autem eveniet voluptas hic sapiente eius minima consequatur excepturi natus ipsum maxime est sunt, corrupti sint cum labore rem! Excepturi aspernatur aut adipisci dolorum inventore porro incidunt temporibus rem magnam. Quibusdam libero eligendi aliquam magnam. Adipisci doloremque similique quo quae sint debitis iste tempora error quis pariatur mollitia eos rem, recusandae molestiae magnam repellat nihil aliquam, quidem nisi. Pariatur placeat molestias soluta, eius asperiores unde rem dolore officiis ex! Accusantium ducimus suscipit at mollitia nesciunt natus quo impedit officiis repellendus vero optio minima odio voluptates numquam aspernatur voluptatibus quas rerum modi, aliquam nulla necessitatibus tempora.</p>
        </div>
    )
}

export default Career